VisaRoom/Models/ApplyCountry.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VisaRoom.Models
{
    public class ApplyCountry
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Country Name")]
        public string ApplyCountryName { get; set; }

        //Relationship
        public List<Candidate> Candidates { get; set; }
  
    }
}

VisaRoom/Controllers/ApplyCountryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using VisaRoom.Data;
using VisaRoom.Data.Services;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    public class ApplyCountryController : Controller
    {

        private readonly IApplyCountryService _service;

        public ApplyCountryController(IApplyCountryService service)
        {
            _service = service;
        }
        public async Task <IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]

        public async Task<IActionResult> Create([Bind("ApplyCountryName")] ApplyCountry applyCountry)
        {
            if(!ModelState.IsValid)
            {
                return View(applyCountry);
            }
            
            await _service.AddAsync(applyCountry);
            return RedirectToAction("Index");
        }

        public async Task <IActionResult> Edit(int id)
        {
            var data = await _service.GetById(id);
            if(data == null)
            {
                return View("Empty");
            }
            return View(data);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(int id, [Bind("ApplyCountryName")] ApplyCountry newApplyCountry)
        {
            if (!ModelState.IsValid)
            {
                return View(newApplyCountry);
            }

            await _service.UpdateAsync(id, newApplyCountry);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");   
        }
    }
}

VisaRoom/Views/ApplyCountry/Create.cshtml
@model ApplyCountry

@{ 
    ViewData["Title"] = "Create a country";
}

<div class="row">
    <p>
        <h4>
            Create a ApplyCountry
        </h4>
    </p>
</div>

<div class="row">
    <div class="col-md-6 offset-3">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="ApplyCountryName" class="control-label"></label>
                <span asp-validation-for="ApplyCountryName"></span>
                <input asp-for="ApplyCountryName" type="text" class="form-control" />
            </div>

            <div class="form-group">
         
                <input type="submit" class="btn btn-primary float-right" value="Create"/>
                <a class="btn btn-info" asp-action="Index">Show All</a>
            </div>

        </form>
    </div>
</div>

VisaRoom/Views/ApplyCountry/Edit.cshtml
@model ApplyCountry

@{ 
    ViewData["Title"] = "Edit a country";
}

<div class="row">
    <p>
        <h4>
           Edit a ApplyCountry
        </h4>
    </p>
</div>

<div class="row">
    <div class="col-md-6 offset-3">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="ApplyCountryName" class="control-label"></label>
                <span asp-validation-for="ApplyCountryName"></span>
                <input asp-for="ApplyCountryName" type="text" class="form-control" />
            </div>

            <div class="form-group">
         
                <input type="submit" class="btn btn-primary float-right" value="Edit"/>
                <a class="btn btn-info" asp-action="Index">Show All</a>
            </div>

        </form>
    </div>
</div>

VisaRoom/Views/ApplyCountry/Index.cshtml
@model IEnumerable<ApplyCountry>

    @{
        ViewData["Title"] = "List of Applicable Country";
    }

<html>
    <body>
        <div class="row">

            <div class="col-md-8 offset 2">
                <table class="table table-striped">
            <thead>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Id)</td>
                    <td>@Html.DisplayNameFor(model => model.ApplyCountryName)</td>
                    <td>Actions</td>
                </tr>

            </thead>

            <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.ApplyCountryName</td>
                            <td>
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a>
                                <a class =" btn btn-primary" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>

                            </td>
                        </tr>
                    }

            </tbody>
        </table>


            </div>

        </div>
         <div class="row">
    <a class="btn btn-info" asp-controller="ApplyCountry" asp-action="Create"><i class="bi bi-plus-circle"></i>Add New Company</a>
</div>
        
    </body>
</html>