VisaRoom/Models/Candidate.cs
using VisaRoom.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;
using VisaRoom.Data.Base;

namespace VisaRoom.Models
{
    public class Candidate : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string CandidateImage { get; set; }
        public string CandidateName { get; set; }
        public string CandidateCity { get; set; }
        public string CandidateCountry { get; set; }

        public int CandidatePhone { get; set; }


        public Gender Gender { get; set; }

        
        //public Experience Experience { get; set; }
        //public Qualification Qualification { get; set; }

        //Relationship

        public string CandidateUserId { get; set; }
        [ForeignKey(nameof(CandidateUserId))]  
        public ApplicationUser userCandidate { get; set; }

        public int ApplyCountryId { get; set; }
        [ForeignKey("ApplyCountryId")]
        public ApplyCountry ApplyCountryObj { get; set; }

        public int VisaTypeId { get; set; }
        [ForeignKey("VisaTypeId")]
        public VisaType VisaTypeObj { get; set; }

        public string Certificate { get; set; }
        public string Certificate2 { get; set; }
        public string Certificate3 { get; set; }
        public string Certificate4 { get; set; }
       

        public List<Candidate_Company> Candidate_CompanyObj { get; set; }
        public List<Candidate_Qualification> Candidate_QualificationsObj { get; set; }

        public List<Candidate_Experience> Candidate_ExperienceObj { get; set; }

        public List<Candidate_Employer> Candidate_EmployerObj { get; set; }

        public List<Employer_Request> Employer_RequestObj { get; set; }

        public List<Approved_Requests> Approved_RequestsObj { get; set; }








    }
}

VisaRoom/Models/Employer_Request.cs
namespace VisaRoom.Models
{
    public class Employer_Request
    {
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public int CandidateId { get; set; }
        public Candidate Candidate { get; set; }
    }
}

VisaRoom/Controllers/CandidateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using VisaRoom.Data;
using VisaRoom.Data.Services;
using VisaRoom.Data.ViewModels;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    
    public class CandidateController : Controller
    {
        private readonly ICandidateService _service;
        public readonly IWebHostEnvironment _webHostEnvironment;

        public CandidateController(ICandidateService service, IWebHostEnvironment webHostEnvironment)
        {
            _service = service;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()


        {
            var data = await _service.GetAllAsync(x => x.ApplyCountryObj, x => x.VisaTypeObj);
            return View(data);
        }

        public async Task<IActionResult> GetByIds(int id)
        {
            var result = await _service.GetByIdAsync(id);
            return View(result);
        }

        
        public IActionResult CandidateHome()
        {
            return View("CandidateHome");
        }
        [HttpGet]
        public async Task <IActionResult> Details(int id)
            
        {
               var result = await _service.GetById(id);
               return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> CDetails()

        {
            string newUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var result = await _service.GetByUserId(newUser);
            var candidate = await _service.GetById(result.Id);
            
            return View(candidate);
        }       
        public async Task<IActionResult> Create()
        {
            string exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var result = await _service.GetByUserId(exUser);
            if(result != null)
            {
                return RedirectToAction(nameof(CandidateHome));
            }
            
            var dropDownValues = await _service.GetNewCandidateDropdownValues();
            ViewBag.Companiess = new SelectList(dropDownValues.Companies, "Id", "CompanyName");
            ViewBag.Acountryid = new SelectList(dropDownValues.ApplyCountries, "Id", "ApplyCountryName");
            ViewBag.Vtypeid = new SelectList(dropDownValues.VisaTypes, "Id", "VisaTypeName");

            return View();
        }

        [HttpPost]       
        public async Task<IActionResult> Create(CandidateVM candidateVM)
        {

            if (!ModelState.IsValid)
            {
                var dropDownValues = await _service.GetNewCandidateDropdownValues();
                ViewBag.Companiess = new SelectList(dropDownValues.Companies, "Id", "CompanyName");
                ViewBag.Acountryid = new SelectList(dropDownValues.ApplyCountries, "Id", "ApplyCountryName");
                ViewBag.Vtypeid = new SelectList(dropDownValues.VisaTypes, "Id", "VisaTypeName");
                return View(candidateVM);
            }

            string userNew= User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _service.AddAsync(candidateVM, userNew);
            return RedirectToAction(nameof(CandidateHome));
        }
      
        public async Task<IActionResult> CEdit()
        {

            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var candidateId = await _service.GetByUserId(user);
            var result = await _service.GetById(candidateId.Id);

            var qual = new Qualification();
            var exp = new Experience();
            //var result = await _service.GetById(id);

            if (result == null)
            {
                return View("Empty");
            }

            foreach (var item in result.Candidate_QualificationsObj)
            {
                qual.InstituteName = item.Qualification.InstituteName;
                qual.DegreeName = item.Qualification.DegreeName;
                qual.DurationYear = item.Qualification.DurationYear;
                qual.PassingYear = item.Qualification.PassingYear;
                qual.SchoolResult = item.Qualification.SchoolResult;

                qual.InstituteName2 = item.Qualification.InstituteName2;
                qual.DegreeName2 = item.Qualification.DegreeName2;
                qual.DurationYear2 = item.Qualification.DurationYear2;
                qual.PassingYear2 = item.Qualification.PassingYear2;
                qual.CollegeResult = item.Qualification.CollegeResult;

                qual.InstituteName3 = item.Qualification.InstituteName3;
                qual.DegreeName3 = item.Qualification.DegreeName3;
                qual.DurationYear3 = item.Qualification.DurationYear3;
                qual.PassingYear3 = item.Qualification.PassingYear3;
                qual.BachelorResult = item.Qualification.BachelorResult;

                qual.InstituteName4 = item.Qualification.InstituteName4;
                qual.DegreeName4 = item.Qualification.DegreeName4;
                qual.DurationYear4 = item.Qualification.DurationYear4;
                qual.PassingYear4 = item.Qualification.PassingYear4;
                qual.MasterResult = item.Qualification.MasterResult;
            };

            foreach (var items in result.Candidate_ExperienceObj)
            {
                exp.OrganizationName = items.Experience.OrganizationName;
                exp.DesignationName = items.Experience.DesignationName;
                exp.LocationName = items.Experience.LocationName;
                exp.YearsExperience = items.Experience.YearsExperience;
            };

            var data = new CandidateVM()
            {
                Id = result.Id,
                CandidateUserId = result.CandidateUserId,
                CandidateName = result.CandidateName,
                CandidateCity = result.CandidateCity,
                CandidateCountry = result.CandidateCountry,
                CandidatePhone = result.CandidatePhone,
                Gender = result.Gender,
                ApplyCountryId = result.ApplyCountryId,
                VisaTypeId = result.VisaTypeId,
                CompanyIds = result.Candidate_CompanyObj.Select(x => x.ComapnyId).ToList(),
                CandidateImage = result.CandidateImage,
                Certificate = result.Certificate,
                Certificate2 = result.Certificate2,
                Certificate3 = result.Certificate3,
                Certificate4 = result.Certificate4,
                Experience = exp,
                Qualification = qual,

            };

            var dropDownValues = await _service.GetNewCandidateDropdownValues();
            ViewBag.Companiess = new SelectList(dropDownValues.Companies, "Id", "CompanyName");
            ViewBag.Acountryid = new SelectList(dropDownValues.ApplyCountries, "Id", "ApplyCountryName");
            ViewBag.Vtypeid = new SelectList(dropDownValues.VisaTypes, "Id", "VisaTypeName");

            return View(data);
        }   
        public async Task<IActionResult> Edit(int id)
        {

            var qual =new Qualification();
            var exp = new Experience(); 
            var result = await _service.GetById(id);

            if (result == null)
            {
                return View("Empty");
            }

            foreach(var item in result.Candidate_QualificationsObj)
            {
                qual.InstituteName = item.Qualification.InstituteName;
                qual.DegreeName = item.Qualification.DegreeName;
                qual.DurationYear = item.Qualification.DurationYear;
                qual.PassingYear = item.Qualification.PassingYear;  
                qual.SchoolResult = item.Qualification.SchoolResult;

                qual.InstituteName2 = item.Qualification.InstituteName2;
                qual.DegreeName2 = item.Qualification.DegreeName2;
                qual.DurationYear2 = item.Qualification.DurationYear2;
                qual.PassingYear2 = item.Qualification.PassingYear2;
                qual.CollegeResult = item.Qualification.CollegeResult;

                qual.InstituteName3 = item.Qualification.InstituteName3;
                qual.DegreeName3 = item.Qualification.DegreeName3;
                qual.DurationYear3 = item.Qualification.DurationYear3;
                qual.PassingYear3 = item.Qualification.PassingYear3;
                qual.BachelorResult = item.Qualification.BachelorResult;

                qual.InstituteName4 = item.Qualification.InstituteName4;
                qual.DegreeName4 = item.Qualification.DegreeName4;
                qual.DurationYear4 = item.Qualification.DurationYear4;
                qual.PassingYear4 = item.Qualification.PassingYear4;
                qual.MasterResult = item.Qualification.MasterResult;
            };

            foreach(var items in result.Candidate_ExperienceObj)
            {
                exp.OrganizationName = items.Experience.OrganizationName;
                exp.DesignationName = items.Experience.DesignationName;
                exp.LocationName = items.Experience.LocationName;
                exp.YearsExperience = items.Experience.YearsExperience;
            };

            var data = new CandidateVM()
            {
                Id = result.Id,
                CandidateUserId = result.CandidateUserId,
                CandidateName = result.CandidateName,
                CandidateCity = result.CandidateCity,
                CandidateCountry = result.CandidateCountry,
                CandidatePhone = result.CandidatePhone,
                Gender = result.Gender,
                ApplyCountryId = result.ApplyCountryId,
                VisaTypeId = result.VisaTypeId,
                CompanyIds = result.Candidate_CompanyObj.Select(x => x.ComapnyId).ToList(),

VisaRoom/Controllers/EmployerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using VisaRoom.Data.Services;
using VisaRoom.Data.ViewModels;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    public class EmployerController : Controller
    {

        private readonly IEmployerService _service;
        private readonly ICandidateService _candidate;
        
        public EmployerController(IEmployerService service, ICandidateService candidate)
        {
            _service = service; 
            _candidate = candidate;
        }
        
        public async Task <IActionResult> Index()
        {
            var result = await _service.GetAllAsync();
            return View(result);
        }

        public async Task<IActionResult> EDetails()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            return View(employer);
        }


        public IActionResult EmployerHome()
        {
            return View("EmployerHome");
        }

        public async Task<IActionResult> Details(int id)
        {
            var employer = await _service.GetAll(id);
            return View(employer);
        }


        public async Task<IActionResult> Create()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            if(employer != null)
            {
                return View(nameof(EmployerHome));
            }
            return View();  
        }

        [HttpPost]
   
        public async Task<IActionResult> Create(EmployerVM newEmployerVM)
        {
            if(newEmployerVM == null)
            {
                return View("Empty");
            }

            var newUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _service.AddAsync(newEmployerVM, newUser);
            return RedirectToAction(nameof(Index)); 
        }


        public async Task <IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if(result == null)
            {
                return View("Empty");
            }

            var data = new EmployerVM()
            {               
                EmployerName = result.EmployerName, 
                EmployerPhone = result.EmployerPhone,   
                EmployerCity = result.EmployerCity,
                EmployerCountry = result.EmployerCountry,   
                EmployerCompany = result.EmployerCompany,
                EmployerImage = result.EmployerImage,
            };

            return View(data);
        }

        public async Task<IActionResult> EEdit()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            var result = await _service.GetById(employer.Id);

            
            if (result == null)
            {
                return View("Empty");
            }

            var data = new EmployerVM()
            {
                Id = result.Id, 
                EmployerName = result.EmployerName,
                EmployerPhone = result.EmployerPhone,
                EmployerCity = result.EmployerCity,
                EmployerCountry = result.EmployerCountry,
                EmployerCompany = result.EmployerCompany,
                EmployerImage = result.EmployerImage,
                
            };

            return View(data);
        }

        [HttpPost]
    
        public async Task<IActionResult> Edit(EmployerVM newEmployerVM)
        {
          if(!ModelState.IsValid)
            {
                return View("Empty");
            }

            //var data = await _service.GetById(newEmployerVM.Id);
            await _service.UpdateAsync(newEmployerVM);
            return RedirectToAction(nameof(EmployerHome));
        }

        [HttpPost]

        public async Task<IActionResult> EEdit(EmployerVM newEmployerVM, int id)
        {
            if (!ModelState.IsValid)
            {
                return View("Empty");
            }

            newEmployerVM.Id = id;  

            //var data = await _service.GetById(newEmployerVM.Id);
            await _service.UpdateAsync(newEmployerVM);
            return RedirectToAction(nameof(EmployerHome));
        }

        public async Task <IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id); 
            return RedirectToAction(nameof(Index)); 
        }

        public async Task<IActionResult> EmployerRequest(int id)
        {
            string userNew = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _candidate.EmployerRequest(id, userNew);
            return RedirectToAction("EmployerHome");

        }

   
        public async Task<IActionResult> MyRequests()
        {
            var requestList = new List<Candidate>();
            var result = await _candidate.GetAll();
            string userNew = User.FindFirstValue(ClaimTypes.NameIdentifier);
            foreach (var item in result)
            {
                foreach(var items in item.Employer_RequestObj)
                {
                    if(userNew == items.UserId)
                    {
                        requestList.Add(item);
                    }
                }
            }
            return View(requestList);    
           

        }
    }
}

VisaRoom/Views/Candidate/ApprovedRequestList.cshtml
@model IEnumerable<Candidate>

@{
    ViewData["Title"] = "List of Companies";
}

<div class="row">
    <p>
        <h4>
            Employer Requests
        </h4>
    </p>
</div>

<div class="row">
    <div class="col-md-8 offset-2">
        <table class="table table-striped flex-column">
            <thead class="align-content-center">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.CandidateImage)</th>
                    <th>@Html.DisplayNameFor(model => model.CandidateName)</th>
                    <th>@Html.DisplayNameFor(model => model.ApplyCountryObj.ApplyCountryName)</th>
                    <th>Employer</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    @foreach (var items in item.Employer_RequestObj)
                    {


                        <tr>
                            <td><img src="~/images/@item.CandidateImage" class="rounded-circle" height="70" width="70" asp-append-version="true" />
                            <td>@item.CandidateName</td>
                            <td>@item.ApplyCountryObj.ApplyCountryName</td>
                            <td><a asp-controller="Employer" asp-action="Details" asp-route-UserId="@items.UserId">@items.User.FullName </a></td>
                            <td><a class="btn btn-info" asp-controller="Candidate" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Details</a></td>
                                

                        </tr>
                    }


                }

            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <a class="btn btn-light" asp-controller="Candidate" asp-action="Create"><i class="bi bi-plus-circle"></i>Add New Candidate</a>
</div>

VisaRoom/Views/Candidate/CDetails.cshtml
@model Candidate

<html>

<body>

    <div class="col-md-10 offset-1">
        <div class="row">

            <div class="col-md-12">

                <div class="col-md-12">
                    <a class="btn btn-primary" asp-controller="Employer" asp-action="EmployerRequest" asp-route-id="@Model.Id"><i class="bi bi-pencil-square"></i>Request Candidate</a>                   
                    </div>

                <div class="col-md-3" style="float:left; display:flex;">
                    <img src="~/images/@Model.CandidateImage" class="square" height="200" width="180" asp-append-version="true" />
                </div>

                <div class="col-md-9" style="float:right;line-height:0.3">
                    <h1 style="text-align:right; ">@Model.CandidateName</h1><br />
                    <h5 style="text-align:right">@Model.CandidateCity</h5><br />
                    <h5 style="text-align:right">@Model.CandidateCountry</h5>
                    <h5 style="text-align:right">@Model.CandidatePhone</h5>
                </div>
               

            </div>

        </div>
        <hr style="border: 5px solid green" />

        <div class="row">
            <div class="col-md-12" style="float:left; line-height:0.3">
                <div>
                    <h3>Professional Experience</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                @foreach(var item in Model.Candidate_ExperienceObj)
                {        
                    <div>                   
                    <br/><h5>Organization: @item.Experience.OrganizationName</h5><br/>
                    <h5>Designation: @item.Experience.DesignationName</h5><br/>
                    <h5>Years of Experience: @item.Experience.YearsExperience</h5><br/>
                    <h5>Location: @item.Experience.LocationName</h5><br/>

                    </div>
                }
                
            </div>
            
        </div>

        <div class="row" style="margin-top:5% auto">
            <div class="col-md-12" style="float:left; line-height:0.3;">
                <div>
                    <br/><h3>Academic Qualification</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                @foreach(var item in Model.Candidate_QualificationsObj)
                {
                    <div>
                    
                    <br/><h5>Institute: @item.Qualification.InstituteName</h5><br/>
                    <h5>Degree: @item.Qualification.DegreeName</h5><br/>
                    <h5>Duration: @item.Qualification.DurationYear</h5><br/>
                    <h5>Passing Year: @item.Qualification.PassingYear</h5><br/>

                    </div>
                }
                
            </div>
            
        </div>

        <div class="row" style="margin-top:5% auto">
            <div class="col-md-12" style="float:left; line-height:0.3;">
                <div>
                    <br/><h3>Personal Information</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                <div>
                    <br/><h5>Full Name: @Model.CandidateName</h5><br/>
                    <h5>Present Address: 55, Sabujbagh, Dhaka-1214</h5><br/>
                    <h5>City: @Model.CandidateCity</h5><br/>
                    <h5>Country: @Model.CandidateCountry</h5><br/>
                    <h5>Marital Status: Married</h5>

                </div>
            </div>
            
        </div>
    </div>



</body>

</html>

VisaRoom/Views/Candidate/CandidateHome.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager;
@using VisaRoom.Data.ViewModels
@model CandidateVM

@{
    ViewData["Title"] = "Candidate Dashboard";
}

<div class="col-md-8 offset-2">
    <h5>@UserManager.GetUserName(User)'s Dashboard</h5>
    
    <div class="col-md-12">
        <a class="btn btn-dark" style="width:200px; height:100px;" asp-controller="Candidate" asp-action="Create"><i class="bi bi-display"></i>Create Profile</a>
        <a class="btn btn-primary" style="width:200px; height:100px;" asp-controller="Candidate" asp-action="CDetails"><i class="bi bi-display"></i>View Resume</a>
        <a class="btn btn-info" style="width:200px; height:100px;" asp-controller="Candidate" asp-action="CEdit"><i class="bi bi-pencil-square"></i>Edit Resume</a>
        <a class="btn btn-danger" style="width:200px; height:100px;" asp-action="CDelete"><i class="bi bi-trash"></i>Delete Resume</a>
    </div>

</div>

VisaRoom/Views/Candidate/Details.cshtml
@model Candidate

<html>

<body>

    <div class="col-md-10 offset-1">
        <div class="row">

            <div class="col-md-12">

                <div class="col-md-12">
                    <a class="btn btn-primary" asp-controller="Employer" asp-action="EmployerRequest" asp-route-id="@Model.Id"><i class="bi bi-pencil-square"></i>Request Candidate</a>                   
                    </div>

                <div class="col-md-3" style="float:left; display:flex;">
                    <img src="~/images/@Model.CandidateImage" class="square" height="200" width="180" asp-append-version="true" />
                </div>

                <div class="col-md-9" style="float:right;line-height:0.3">
                    <h1 style="text-align:right; ">@Model.CandidateName</h1><br />
                    <h5 style="text-align:right">@Model.CandidateCity</h5><br />
                    <h5 style="text-align:right">@Model.CandidateCountry</h5>
                    <h5 style="text-align:right">@Model.CandidatePhone</h5>
                </div>
               

            </div>

        </div>
        <hr style="border: 5px solid green" />

        <div class="row">
            <div class="col-md-12" style="float:left; line-height:0.3">
                <div>
                    <h3>Professional Experience</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                @foreach(var item in Model.Candidate_ExperienceObj)
                {        
                    <div>                   
                    <br/><h5>Organization: @item.Experience.OrganizationName</h5><br/>
                    <h5>Designation: @item.Experience.DesignationName</h5><br/>
                    <h5>Years of Experience: @item.Experience.YearsExperience</h5><br/>
                    <h5>Location: @item.Experience.LocationName</h5><br/>

                    </div>
                }
                
            </div>
            
        </div>

        <div class="row" style="margin-top:5% auto">
            <div class="col-md-12" style="float:left; line-height:0.3;">
                <div>
                    <br/><h3>Academic Qualification</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                @foreach(var item in Model.Candidate_QualificationsObj)
                {
                    <div>
                    
                    <br/><h5>Institute: @item.Qualification.InstituteName</h5><br/>
                    <h5>Degree: @item.Qualification.DegreeName</h5><br/>
                    <h5>Duration: @item.Qualification.DurationYear</h5><br/>
                    <h5>Passing Year: @item.Qualification.PassingYear</h5><br/>

                    </div>
                }
                
            </div>
            
        </div>

        <div class="row" style="margin-top:5% auto">
            <div class="col-md-12" style="float:left; line-height:0.3;">
                <div>
                    <br/><h3>Personal Information</h3>
                    <hr style="width:10%; border: 2px solid green" />
                </div>
                
                <div>
                    <br/><h5>Full Name: @Model.CandidateName</h5><br/>
                    <h5>Present Address: 55, Sabujbagh, Dhaka-1214</h5><br/>
                    <h5>City: @Model.CandidateCity</h5><br/>
                    <h5>Country: @Model.CandidateCountry</h5><br/>
                    <h5>Marital Status: Married</h5>

                </div>
            </div>
            
        </div>
    </div>



</body>

</html>

VisaRoom/Views/Candidate/EmployerRequests.cshtml
@model IEnumerable<Candidate>

@{
    ViewData["Title"] = "List of Companies";
}

<div class="row">
    <p>
        <h4>
            List of Candidates
        </h4>
    </p>
</div>

<div class="row">
    <div class="col-md-8 offset-2">
        <table class="table table-striped flex-column ">
            <thead class="align-content-center">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@Html.DisplayNameFor(model => model.CandidateImage)</th>
                    <th>@Html.DisplayNameFor(model => model.CandidateName)</th>
                    <th>Applied Country</th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td><img src="~/images/@item.CandidateImage" class="rounded-circle" height="70" width="70" asp-append-version="true" /> 
                        <td>@item.CandidateName</td>
                        <td>@item.ApplyCountryObj.ApplyCountryName</td>
                        <td>
                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id" ><i class="bi bi-pencil-square"></i>Edit</a> |
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id" ><i class="bi bi-trash"></i>Delete</a> |
                            <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id" ><i class="bi bi-eye-fill"></i>Details</a> |
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <a class="btn btn-light" asp-controller="Candidate" asp-action="Create"><i class="bi bi-plus-circle"></i>Add New Candidate</a>
</div>