VisaRoom/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using VisaRoom.Data;
using VisaRoom.Data.Services;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _service;
        public CompanyController(ICompanyService service)
        {
            _service = service;
        }
        
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }

        public IActionResult Create()
        {
            
            return View();  
        }

        [HttpPost]
        public async Task <IActionResult> Create ([Bind("CompanyName,CompanyLocation")] Company company)
        {
            /*if (!ModelState.IsValid)
            {
                return View(company);
            }*/

            await _service.AddAsync(company);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var details = await _service.GetById(id);
            if (details == null)
            {
                return View("Empty");
            }
            return View(details);   
        }

        public async Task<IActionResult> Edit(int id)
        {
            var data = await _service.GetById(id);
            if(data == null)
            {
                return View("Empty");
            }
            return View(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("CompanyName,CompanyLocation")] Company newCompany)
        {
            /*if (!ModelState.IsValid)
            {
                return View(newCompany);
            }*/
            await _service.UpdateAsync(id, newCompany);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

VisaRoom/Controllers/EmployerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using VisaRoom.Data.Services;
using VisaRoom.Data.ViewModels;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    public class EmployerController : Controller
    {

        private readonly IEmployerService _service;
        private readonly ICandidateService _candidate;
        
        public EmployerController(IEmployerService service, ICandidateService candidate)
        {
            _service = service; 
            _candidate = candidate;
        }
        
        public async Task <IActionResult> Index()
        {
            var result = await _service.GetAllAsync();
            return View(result);
        }

        public async Task<IActionResult> EDetails()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            return View(employer);
        }


        public IActionResult EmployerHome()
        {
            return View("EmployerHome");
        }

        public async Task<IActionResult> Details(int id)
        {
            var employer = await _service.GetAll(id);
            return View(employer);
        }


        public async Task<IActionResult> Create()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            if(employer != null)
            {
                return View(nameof(EmployerHome));
            }
            return View();  
        }

        [HttpPost]
   
        public async Task<IActionResult> Create(EmployerVM newEmployerVM)
        {
            if(newEmployerVM == null)
            {
                return View("Empty");
            }

            var newUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _service.AddAsync(newEmployerVM, newUser);
            return RedirectToAction(nameof(Index)); 
        }


        public async Task <IActionResult> Edit(int id)
        {
            var result = await _service.GetByIdAsync(id);
            if(result == null)
            {
                return View("Empty");
            }

            var data = new EmployerVM()
            {               
                EmployerName = result.EmployerName, 
                EmployerPhone = result.EmployerPhone,   
                EmployerCity = result.EmployerCity,
                EmployerCountry = result.EmployerCountry,   
                EmployerCompany = result.EmployerCompany,
                EmployerImage = result.EmployerImage,
            };

            return View(data);
        }

        public async Task<IActionResult> EEdit()
        {
            var exUser = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employer = await _service.GetByUserId(exUser);
            var result = await _service.GetById(employer.Id);

            
            if (result == null)
            {
                return View("Empty");
            }

            var data = new EmployerVM()
            {
                Id = result.Id, 
                EmployerName = result.EmployerName,
                EmployerPhone = result.EmployerPhone,
                EmployerCity = result.EmployerCity,
                EmployerCountry = result.EmployerCountry,
                EmployerCompany = result.EmployerCompany,
                EmployerImage = result.EmployerImage,
                
            };

            return View(data);
        }

        [HttpPost]
    
        public async Task<IActionResult> Edit(EmployerVM newEmployerVM)
        {
          if(!ModelState.IsValid)
            {
                return View("Empty");
            }

            //var data = await _service.GetById(newEmployerVM.Id);
            await _service.UpdateAsync(newEmployerVM);
            return RedirectToAction(nameof(EmployerHome));
        }

        [HttpPost]

        public async Task<IActionResult> EEdit(EmployerVM newEmployerVM, int id)
        {
            if (!ModelState.IsValid)
            {
                return View("Empty");
            }

            newEmployerVM.Id = id;  

            //var data = await _service.GetById(newEmployerVM.Id);
            await _service.UpdateAsync(newEmployerVM);
            return RedirectToAction(nameof(EmployerHome));
        }

        public async Task <IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id); 
            return RedirectToAction(nameof(Index)); 
        }

        public async Task<IActionResult> EmployerRequest(int id)
        {
            string userNew = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _candidate.EmployerRequest(id, userNew);
            return RedirectToAction("EmployerHome");

        }

   
        public async Task<IActionResult> MyRequests()
        {
            var requestList = new List<Candidate>();
            var result = await _candidate.GetAll();
            string userNew = User.FindFirstValue(ClaimTypes.NameIdentifier);
            foreach (var item in result)
            {
                foreach(var items in item.Employer_RequestObj)
                {
                    if(userNew == items.UserId)
                    {
                        requestList.Add(item);
                    }
                }
            }
            return View(requestList);    
           

        }
    }
}

VisaRoom/Controllers/VisaTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using VisaRoom.Data;
using VisaRoom.Data.Services;
using VisaRoom.Models;

namespace VisaRoom.Controllers
{
    public class VisaTypeController : Controller
    {
        private readonly IVisaTypeServices _service;

        public VisaTypeController(IVisaTypeServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("VisaTypeName")]VisaType visaType) 
        {
            if (!ModelState.IsValid)
            {
                return View(visaType);
            }

            await _service.AddAsync(visaType);
            return RedirectToAction("Index");   
        }


       public async Task<IActionResult> Details(int id)
        {
            var data = await _service.GetById(id);
            if(data == null)
            {
                return View("Empty");
            }
            return View(data);  
        }
        
        public async Task <IActionResult> Edit(int id)
        {
            var data = await _service.GetById(id);
            if (data == null)
            {
                return View("Empty");
            }
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("VisaTypeName")] VisaType visaType, int id)
        {
            if (!ModelState.IsValid)
            {
                return View(visaType);
            }

            await _service.UpdateAsync(id, visaType);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
    }
}

VisaRoom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VisaRoom</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/768c287031.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="col-md-3" style="float:left; display:flex;">
                   <img src="~/images/logo.jpg" asp-action="Index" class="square" height="60%" width="70%" asp-append-version="true" />
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidate" asp-action="CandidateHome">Candidate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employer" asp-action="EmployerHome">Employer</a>
                        </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Employer" asp-action="Index"><i class="bi bi-camera-reels"></i> Employer</a>
                                    <a class="dropdown-item" asp-controller="Candidate" asp-action="Index"><i class="bi bi-headset"></i> Candidate</a>
                                    <a class="dropdown-item" asp-controller="Company" asp-action="Index"><i class="bi bi-person-square"></i> Company</a>
                                    <a class="dropdown-item" asp-controller="VisaType" asp-action="Index"><i class="bi bi-person-square"></i> Visa Type</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Index"><i class="bi bi-person-square"></i> User List</a>
                                </div>
                            </li>

                            <li>

                            </li>
                      
                    </ul>
                    }
                    
                       <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VisaRoom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VisaRoom/Views/Shared/_identity.cshtml
@using Microsoft.AspNetCore.Identity


@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    }
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i>Hello @UserManager.GetUserName(User)!
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i>Users
                    </a>
                </li>
            }

             @if (User.IsInRole("Employer"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="EmployerHome">
                        <i class="bi bi-people"></i>Home
                    </a>
                </li>
            }

             @if (User.IsInRole("Candidate"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="CandidateHome">
                        <i class="bi bi-people"></i>Home
                    </a>
                </li>
            }



        </ul>
    </div>

    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>Log Out
        </button>
    </form>
}